# 設定資料庫連接
# 3306是連接 mysql 的 port；p111150512 是要連接的資料庫名稱
# rewriteBatchedStatements=true: 可以批次新增
spring.datasource.url=jdbc:mysql://localhost:3306/quiz1150512?serverTimezone=Asia/Taipei&useSSL=false&rewriteBatchedStatements=true
# 拆成三個部分來看
# jdbc:mysql://localhost:3306/quiz1150512（核心位址）
# serverTimezone=Asia/Taipei（時區設定）
# useSSL=false
# rewriteBatchedStatements=true（效能優化）

spring.datasource.username=root
spring.datasource.password=root
# 登入 MySQL 資料庫時驗證身份用的管理員帳號 (root) 與密碼 (root)。Spring Boot 會拿這組帳密去取得操作資料庫的權限。
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 指定 Java 連接 MySQL 所使用的 JDBC 驅動類別名稱（這個類別就來自你剛才在 build.gradle 說明的 com.mysql:mysql-connector-j 套件）。告訴 Spring Boot：「請用這個類別作為溝通橋樑來發送 SQL 指令」。
spring.jpa.show-sql=true
# 每當你在 Java 執行 JPA 操作（例如呼叫 repository.save() 或 repository.findAll()）時，Eclipse 下方的 Console 面板就會即時印出 JPA 底層真正幫你組好的 SQL 語法。這樣你可以很清楚地知道 JPA 背後到底對 MySQL 做了什麼事！

server.port=8081